name: srscs
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  firebase_core: ^2.27.0
  cached_network_image: ^3.3.1
  provider: ^6.1.5
  path_provider: ^2.1.5
  firebase_storage: ^11.6.9
  firebase_auth: ^4.5.0
  cloud_firestore: ^4.4.0
  firebase_messaging: ^14.7.6
  flutter_local_notifications: ^17.2.3
  syncfusion_flutter_charts: ^27.2.5
  flutter_expandable_fab: ^2.5.0
  intl: ^0.19.0
  shimmer: ^3.0.0
  animated_number: ^1.0.2
  animated_flip_counter: ^0.3.4
  image_picker: ^1.1.2
  ml_algo: ^16.17.13
  ml_dataframe: ^1.6.0
  flutter_launcher_icons: ^0.14.4
  # Additional packages for new modules
  sqflite: ^2.3.0
  geolocator: ^10.1.0
  permission_handler: ^11.0.1
  firebase_database: ^10.4.0
  connectivity_plus: ^5.0.2
  uuid: ^4.2.1
  file_picker: ^8.0.0
  video_player: ^2.8.1
  audioplayers: ^5.2.1
  dartz: ^0.10.1
  url_launcher: ^6.2.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo"

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.jpeg
