// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw4lWIuQhGQd5MFbDnbyIt36u6USKBn34',
    appId: '1:460284440327:web:056d4ffaee23f2c646dfa2',
    messagingSenderId: '460284440327',
    projectId: 'srscs-58227',
    authDomain: 'srscs-58227.firebaseapp.com',
    storageBucket: 'srscs-58227.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw4lWIuQhGQd5MFbDnbyIt36u6USKBn34',
    appId: '1:460284440327:android:056d4ffaee23f2c646dfa2',
    messagingSenderId: '460284440327',
    projectId: 'srscs-58227',
    storageBucket: 'srscs-58227.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw4lWIuQhGQd5MFbDnbyIt36u6USKBn34',
    appId: '1:460284440327:ios:056d4ffaee23f2c646dfa2',
    messagingSenderId: '460284440327',
    projectId: 'srscs-58227',
    storageBucket: 'srscs-58227.firebasestorage.app',
    iosBundleId: 'com.example.srscs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw4lWIuQhGQd5MFbDnbyIt36u6USKBn34',
    appId: '1:460284440327:ios:056d4ffaee23f2c646dfa2',
    messagingSenderId: '460284440327',
    projectId: 'srscs-58227',
    storageBucket: 'srscs-58227.firebasestorage.app',
    iosBundleId: 'com.example.srscs',
  );
}
